version: '3'
services:
  mysql:
    image: arm64v8/mysql
    restart: unless-stopped
    container_name: mysql56-container
    ports:
      - '127.0.0.1:3356:3306'
    environment:
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - /var/lib/mysql56-data:/var/lib/mysql